# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test CI

# Run on basicly every change to the tree
on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:

  # Initialize
  initialize:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 15.x ]

  # Checkout the repository in its current state
  checkout:
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

  # Install all node modules
  install:
    steps:
      - run: npm ci

  # Build package
  build:
    steps:
      - run: npm run build --if-present

  # Run tests
  test:
    steps:
      - run: npm run test --if-present
